"""baseline current application schema

Revision ID: 20260720_0001
Revises:
Create Date: 2026-07-20 07:31:20.177868
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '20260720_0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rate_limit_buckets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scope', sa.Text(), nullable=False),
    sa.Column('subject_type', sa.Text(), nullable=False),
    sa.Column('subject_hash', sa.Text(), nullable=False),
    sa.Column('window_started_at', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.Integer(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.Text(), nullable=False),
    sa.CheckConstraint('attempts > 0', name='ck_rate_limit_bucket_attempts'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scope', 'subject_type', 'subject_hash', 'window_started_at', name='uq_rate_limit_bucket_subject_window')
    )
    with op.batch_alter_table('rate_limit_buckets', schema=None) as batch_op:
        batch_op.create_index('ix_rate_limit_buckets_expires_at', ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_rate_limit_buckets_id'), ['id'], unique=False)
        batch_op.create_index('ix_rate_limit_buckets_subject', ['scope', 'subject_type', 'subject_hash'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.Text(), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.Column('last_login_at', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('admin_audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('target_user_id', sa.Integer(), nullable=True),
    sa.Column('resource_type', sa.Text(), nullable=False),
    sa.Column('resource_id', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('detail_summary', sa.Text(), nullable=False),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.CheckConstraint("status IN ('success', 'failed')", name='ck_admin_audit_logs_status'),
    sa.ForeignKeyConstraint(['admin_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['target_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('admin_audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_admin_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index('ix_admin_audit_logs_action_created', ['action', 'created_at'], unique=False)
        batch_op.create_index('ix_admin_audit_logs_admin_created', ['admin_user_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_admin_audit_logs_admin_user_id'), ['admin_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_admin_audit_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_admin_audit_logs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_admin_audit_logs_status'), ['status'], unique=False)
        batch_op.create_index('ix_admin_audit_logs_status_created', ['status', 'created_at'], unique=False)
        batch_op.create_index('ix_admin_audit_logs_target_created', ['target_user_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_admin_audit_logs_target_user_id'), ['target_user_id'], unique=False)

    op.create_table('auth_security_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('session_ref', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('auth_security_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_auth_security_events_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_auth_security_events_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_auth_security_events_id'), ['id'], unique=False)
        batch_op.create_index('ix_auth_security_events_type_created', ['event_type', 'created_at'], unique=False)
        batch_op.create_index('ix_auth_security_events_user_created', ['user_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_auth_security_events_user_id'), ['user_id'], unique=False)

    op.create_table('auth_sessions',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('refresh_token_hash', sa.Text(), nullable=False),
    sa.Column('csrf_token_hash', sa.Text(), nullable=False),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.Column('last_seen_at', sa.Text(), nullable=False),
    sa.Column('expires_at', sa.Text(), nullable=False),
    sa.Column('revoked_at', sa.Text(), nullable=True),
    sa.Column('revoke_reason', sa.Text(), nullable=True),
    sa.Column('token_version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('user_agent_hash', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('auth_sessions', schema=None) as batch_op:
        batch_op.create_index('ix_auth_sessions_expires_at', ['expires_at'], unique=False)
        batch_op.create_index('ix_auth_sessions_revoked_at', ['revoked_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_auth_sessions_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_auth_sessions_user_revoked', ['user_id', 'revoked_at'], unique=False)

    op.create_table('daily_usage_counters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('usage_type', sa.Text(), nullable=False),
    sa.Column('usage_date', sa.Text(), nullable=False),
    sa.Column('used', sa.Integer(), nullable=False),
    sa.Column('reserved', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.Text(), nullable=False),
    sa.CheckConstraint('reserved >= 0', name='ck_daily_usage_counters_reserved'),
    sa.CheckConstraint('used >= 0', name='ck_daily_usage_counters_used'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'usage_type', 'usage_date', name='uq_daily_usage_counters_user_type_date')
    )
    with op.batch_alter_table('daily_usage_counters', schema=None) as batch_op:
        batch_op.create_index('ix_daily_usage_counters_date_type', ['usage_date', 'usage_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_daily_usage_counters_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_daily_usage_counters_usage_date'), ['usage_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_daily_usage_counters_usage_type'), ['usage_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_daily_usage_counters_user_id'), ['user_id'], unique=False)

    op.create_table('files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('file_id', sa.Text(), nullable=False),
    sa.Column('filename', sa.Text(), nullable=False),
    sa.Column('file_type', sa.Text(), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('size_bytes', sa.Integer(), server_default='0', nullable=False),
    sa.Column('content_sha256', sa.Text(), nullable=True),
    sa.Column('upload_idempotency_key_hash', sa.Text(), nullable=True),
    sa.Column('category', sa.Text(), server_default='other', nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.Text(), nullable=False),
    sa.CheckConstraint('size_bytes >= 0', name='ck_files_size_bytes'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_files_file_id'), ['file_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_files_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_files_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ux_files_user_upload_idempotency', ['user_id', 'upload_idempotency_key_hash'], unique=True, sqlite_where=sa.text('upload_idempotency_key_hash IS NOT NULL'))

    op.create_table('history_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('record_id', sa.Text(), nullable=False),
    sa.Column('mode', sa.Text(), nullable=False),
    sa.Column('user_input', sa.Text(), nullable=False),
    sa.Column('ai_output', sa.Text(), nullable=False),
    sa.Column('sources', sa.Text(), nullable=True),
    sa.Column('used_web_search', sa.Integer(), nullable=False),
    sa.Column('web_sources', sa.Text(), nullable=True),
    sa.Column('route_reason', sa.Text(), nullable=True),
    sa.Column('execution_steps', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('history_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_history_records_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_history_records_record_id'), ['record_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_history_records_user_id'), ['user_id'], unique=False)

    op.create_table('interview_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('session_id', sa.Text(), nullable=False),
    sa.Column('interview_type', sa.Text(), nullable=False),
    sa.Column('job_description', sa.Text(), nullable=True),
    sa.Column('question_index', sa.Integer(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('user_answer', sa.Text(), nullable=False),
    sa.Column('score_total', sa.Integer(), nullable=False),
    sa.Column('content_relevance', sa.Integer(), nullable=False),
    sa.Column('personal_match', sa.Integer(), nullable=False),
    sa.Column('technical_accuracy', sa.Integer(), nullable=False),
    sa.Column('structure_score', sa.Integer(), nullable=False),
    sa.Column('risk_control', sa.Integer(), nullable=False),
    sa.Column('main_problems', sa.Text(), nullable=True),
    sa.Column('suggestions', sa.Text(), nullable=True),
    sa.Column('reference_answer', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('interview_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_interview_records_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_interview_records_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_interview_records_user_id'), ['user_id'], unique=False)

    op.create_table('registration_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invite_code_hash', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.Text(), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.CheckConstraint('id = 1', name='ck_registration_settings_singleton'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('target_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('job_title', sa.Text(), nullable=False),
    sa.Column('company_name', sa.Text(), nullable=False),
    sa.Column('jd_text', sa.Text(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('target_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_target_jobs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_target_jobs_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_target_jobs_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ux_target_jobs_active_user', ['user_id'], unique=True, sqlite_where=sa.text('is_active = 1'))

    op.create_table('upload_reservations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reservation_id', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.CheckConstraint('size_bytes > 0', name='ck_upload_reservation_size'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('upload_reservations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_upload_reservations_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_upload_reservations_reservation_id'), ['reservation_id'], unique=True)
        batch_op.create_index('ix_upload_reservations_user_expires', ['user_id', 'expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_upload_reservations_user_id'), ['user_id'], unique=False)

    op.create_table('usage_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('usage_type', sa.Text(), nullable=False),
    sa.Column('usage_date', sa.Text(), nullable=False),
    sa.Column('idempotency_key', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('related_resource_type', sa.Text(), nullable=True),
    sa.Column('related_resource_id', sa.Text(), nullable=True),
    sa.Column('error_type', sa.Text(), nullable=True),
    sa.Column('reserved_at', sa.Text(), nullable=False),
    sa.Column('completed_at', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.Text(), nullable=False),
    sa.CheckConstraint("status IN ('reserved', 'succeeded', 'released', 'failed')", name='ck_usage_events_status'),
    sa.CheckConstraint("usage_type IN ('chat', 'job_analysis', 'interview_evaluation', 'multi_agent_task', 'resume_generation', 'llm_call', 'embedding_call', 'web_search')", name='ck_usage_events_type'),
    sa.CheckConstraint('amount > 0', name='ck_usage_events_amount'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'usage_type', 'idempotency_key', name='uq_usage_events_user_type_key')
    )
    with op.batch_alter_table('usage_events', schema=None) as batch_op:
        batch_op.create_index('ix_usage_events_date_type', ['usage_date', 'usage_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_usage_events_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_usage_events_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_usage_events_usage_date'), ['usage_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_usage_events_usage_type'), ['usage_type'], unique=False)
        batch_op.create_index('ix_usage_events_user_date_type_status', ['user_id', 'usage_date', 'usage_type', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_usage_events_user_id'), ['user_id'], unique=False)

    op.create_table('user_data_deletion_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('deleted_counts', sa.JSON(), nullable=False),
    sa.Column('failure_count', sa.Integer(), nullable=False),
    sa.Column('detail_summary', sa.Text(), nullable=False),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.CheckConstraint("status IN ('success', 'failed')", name='ck_user_data_deletion_logs_status'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_data_deletion_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_data_deletion_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_data_deletion_logs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_data_deletion_logs_status'), ['status'], unique=False)
        batch_op.create_index('ix_user_data_deletion_logs_user_created', ['user_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_data_deletion_logs_user_id'), ['user_id'], unique=False)

    op.create_table('user_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=False),
    sa.Column('target_direction', sa.Text(), nullable=False),
    sa.Column('self_introduction', sa.Text(), nullable=False),
    sa.Column('technical_skills', sa.Text(), nullable=False),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_profiles_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_profiles_user_id'), ['user_id'], unique=True)

    op.create_table('interview_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('target_job_id', sa.Integer(), nullable=True),
    sa.Column('previous_session_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('mode', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('planned_main_questions', sa.Integer(), nullable=False),
    sa.Column('current_main_question', sa.Integer(), nullable=False),
    sa.Column('selected_project_file_ids', sa.JSON(), nullable=False),
    sa.Column('interview_plan', sa.JSON(), nullable=True),
    sa.Column('agent_execution_summary', sa.JSON(), nullable=True),
    sa.Column('overall_score', sa.Float(), nullable=True),
    sa.Column('dimension_scores', sa.JSON(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('improvement_status', sa.Text(), server_default='pending', nullable=False),
    sa.Column('improvement_summary', sa.Text(), nullable=True),
    sa.Column('next_round_strategy', sa.Text(), nullable=True),
    sa.Column('improvement_generated_at', sa.Text(), nullable=True),
    sa.Column('improvement_error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.Text(), nullable=True),
    sa.Column('completed_at', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.Text(), nullable=False),
    sa.CheckConstraint("improvement_status IN ('pending', 'generating', 'completed', 'failed')", name='ck_interview_sessions_improvement_status'),
    sa.CheckConstraint("mode IN ('quick', 'standard', 'deep_dive')", name='ck_interview_sessions_mode'),
    sa.CheckConstraint("status IN ('draft', 'in_progress', 'completed', 'cancelled')", name='ck_interview_sessions_status'),
    sa.CheckConstraint('current_main_question >= 0', name='ck_interview_sessions_current_question'),
    sa.CheckConstraint('overall_score IS NULL OR (overall_score >= 0 AND overall_score <= 100)', name='ck_interview_sessions_overall_score'),
    sa.CheckConstraint('planned_main_questions > 0', name='ck_interview_sessions_planned_questions'),
    sa.ForeignKeyConstraint(['previous_session_id'], ['interview_sessions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['target_job_id'], ['target_jobs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('interview_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_interview_sessions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_interview_sessions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_interview_sessions_improvement_status'), ['improvement_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_interview_sessions_mode'), ['mode'], unique=False)
        batch_op.create_index(batch_op.f('ix_interview_sessions_previous_session_id'), ['previous_session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_interview_sessions_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_interview_sessions_target_job_id'), ['target_job_id'], unique=False)
        batch_op.create_index('ix_interview_sessions_user_created', ['user_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_interview_sessions_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_interview_sessions_user_mode', ['user_id', 'mode'], unique=False)
        batch_op.create_index('ix_interview_sessions_user_status', ['user_id', 'status'], unique=False)

    op.create_table('agent_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Text(), nullable=False),
    sa.Column('request_id', sa.Text(), nullable=True),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('agent_name', sa.Text(), nullable=False),
    sa.Column('prompt_version', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.CheckConstraint("agent_name IN ('supervisor', 'evidence', 'evaluation', 'interviewer', 'improvement', 'resume')", name='ck_agent_runs_agent_name'),
    sa.CheckConstraint("status IN ('success', 'error')", name='ck_agent_runs_status'),
    sa.CheckConstraint('latency_ms >= 0', name='ck_agent_runs_latency'),
    sa.ForeignKeyConstraint(['session_id'], ['interview_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_runs_agent_name'), ['agent_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_runs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_runs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_runs_request_id'), ['request_id'], unique=False)
        batch_op.create_index('ix_agent_runs_run_id', ['run_id'], unique=False)
        batch_op.create_index('ix_agent_runs_session_created', ['session_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_runs_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_runs_status'), ['status'], unique=False)
        batch_op.create_index('ix_agent_runs_user_created', ['user_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_runs_user_id'), ['user_id'], unique=False)

    op.create_table('interview_turns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('main_question_number', sa.Integer(), nullable=False),
    sa.Column('follow_up_number', sa.Integer(), nullable=False),
    sa.Column('parent_turn_id', sa.Integer(), nullable=True),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('question_type', sa.Text(), nullable=False),
    sa.Column('user_answer', sa.Text(), nullable=True),
    sa.Column('technical_accuracy_score', sa.Integer(), nullable=True),
    sa.Column('evidence_consistency_score', sa.Integer(), nullable=True),
    sa.Column('answer_depth_score', sa.Integer(), nullable=True),
    sa.Column('expression_structure_score', sa.Integer(), nullable=True),
    sa.Column('job_match_score', sa.Integer(), nullable=True),
    sa.Column('total_score', sa.Integer(), nullable=True),
    sa.Column('evaluation_summary', sa.Text(), nullable=True),
    sa.Column('problems', sa.JSON(), nullable=True),
    sa.Column('optimized_answer', sa.Text(), nullable=True),
    sa.Column('modification_reason', sa.Text(), nullable=True),
    sa.Column('has_evidence_conflict', sa.Boolean(), nullable=False),
    sa.Column('evidence_conflicts', sa.JSON(), nullable=True),
    sa.Column('evidence_sources', sa.JSON(), nullable=True),
    sa.Column('evaluation_source_ids', sa.JSON(), nullable=True),
    sa.Column('unsupported_claims', sa.JSON(), nullable=True),
    sa.Column('strengths', sa.JSON(), nullable=True),
    sa.Column('answered_at', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.Text(), nullable=False),
    sa.CheckConstraint("question_type IN ('main', 'follow_up')", name='ck_interview_turns_question_type'),
    sa.CheckConstraint('answer_depth_score IS NULL OR (answer_depth_score >= 0 AND answer_depth_score <= 100)', name='ck_interview_turns_answer_depth_score'),
    sa.CheckConstraint('evidence_consistency_score IS NULL OR (evidence_consistency_score >= 0 AND evidence_consistency_score <= 100)', name='ck_interview_turns_evidence_consistency_score'),
    sa.CheckConstraint('expression_structure_score IS NULL OR (expression_structure_score >= 0 AND expression_structure_score <= 100)', name='ck_interview_turns_expression_structure_score'),
    sa.CheckConstraint('follow_up_number >= 0 AND follow_up_number <= 2', name='ck_interview_turns_follow_up_number'),
    sa.CheckConstraint('job_match_score IS NULL OR (job_match_score >= 0 AND job_match_score <= 100)', name='ck_interview_turns_job_match_score'),
    sa.CheckConstraint('main_question_number > 0', name='ck_interview_turns_main_question'),
    sa.CheckConstraint('technical_accuracy_score IS NULL OR (technical_accuracy_score >= 0 AND technical_accuracy_score <= 100)', name='ck_interview_turns_technical_accuracy_score'),
    sa.CheckConstraint('total_score IS NULL OR (total_score >= 0 AND total_score <= 100)', name='ck_interview_turns_total_score'),
    sa.ForeignKeyConstraint(['parent_turn_id'], ['interview_turns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['interview_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'main_question_number', 'follow_up_number', name='uq_interview_turns_question_follow_up'),
    sa.UniqueConstraint('session_id', 'sequence_number', name='uq_interview_turns_session_sequence')
    )
    with op.batch_alter_table('interview_turns', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_interview_turns_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_interview_turns_parent_turn_id'), ['parent_turn_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_interview_turns_session_id'), ['session_id'], unique=False)
        batch_op.create_index('ix_interview_turns_session_main', ['session_id', 'main_question_number'], unique=False)
        batch_op.create_index('ix_interview_turns_user_created', ['user_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_interview_turns_user_id'), ['user_id'], unique=False)

    op.create_table('resume_project_descriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('target_job_id', sa.Integer(), nullable=True),
    sa.Column('project_file_ids', sa.JSON(), nullable=False),
    sa.Column('project_name', sa.Text(), nullable=False),
    sa.Column('one_line_summary', sa.Text(), nullable=False),
    sa.Column('concise_bullets', sa.JSON(), nullable=False),
    sa.Column('detailed_description', sa.Text(), nullable=False),
    sa.Column('technical_stack', sa.JSON(), nullable=False),
    sa.Column('responsibilities', sa.JSON(), nullable=False),
    sa.Column('challenges', sa.JSON(), nullable=False),
    sa.Column('solutions', sa.JSON(), nullable=False),
    sa.Column('outcomes', sa.JSON(), nullable=False),
    sa.Column('interview_talking_points', sa.JSON(), nullable=False),
    sa.Column('warnings', sa.JSON(), nullable=False),
    sa.Column('evidence_source_ids', sa.JSON(), nullable=False),
    sa.Column('prompt_version', sa.Text(), nullable=False),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['interview_sessions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['target_job_id'], ['target_jobs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('resume_project_descriptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_resume_project_descriptions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_resume_project_descriptions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_resume_project_descriptions_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_resume_project_descriptions_target_job_id'), ['target_job_id'], unique=False)
        batch_op.create_index('ix_resume_project_descriptions_user_created', ['user_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_resume_project_descriptions_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_resume_project_descriptions_user_session', ['user_id', 'session_id'], unique=False)

    op.create_table('improvement_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('turn_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('completion_criteria', sa.Text(), server_default='', nullable=False),
    sa.Column('category', sa.Text(), nullable=False),
    sa.Column('priority', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('dedupe_key', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.Column('completed_at', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.Text(), nullable=False),
    sa.CheckConstraint("category IN ('technical', 'project_evidence', 'answer_depth', 'expression', 'job_match', 'resume')", name='ck_improvement_tasks_category'),
    sa.CheckConstraint("priority IN ('low', 'medium', 'high')", name='ck_improvement_tasks_priority'),
    sa.CheckConstraint("status IN ('pending', 'completed')", name='ck_improvement_tasks_status'),
    sa.ForeignKeyConstraint(['session_id'], ['interview_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['turn_id'], ['interview_turns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('improvement_tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_improvement_tasks_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_improvement_tasks_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_improvement_tasks_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_improvement_tasks_session_id'), ['session_id'], unique=False)
        batch_op.create_index('ix_improvement_tasks_session_status', ['session_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_improvement_tasks_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_improvement_tasks_turn_id'), ['turn_id'], unique=False)
        batch_op.create_index('ix_improvement_tasks_user_category', ['user_id', 'category'], unique=False)
        batch_op.create_index('ix_improvement_tasks_user_created', ['user_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_improvement_tasks_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_improvement_tasks_user_status', ['user_id', 'status'], unique=False)
        batch_op.create_index('ux_improvement_tasks_session_dedupe', ['session_id', 'dedupe_key'], unique=True, sqlite_where=sa.text('dedupe_key IS NOT NULL'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('improvement_tasks', schema=None) as batch_op:
        batch_op.drop_index('ux_improvement_tasks_session_dedupe', sqlite_where=sa.text('dedupe_key IS NOT NULL'))
        batch_op.drop_index('ix_improvement_tasks_user_status')
        batch_op.drop_index(batch_op.f('ix_improvement_tasks_user_id'))
        batch_op.drop_index('ix_improvement_tasks_user_created')
        batch_op.drop_index('ix_improvement_tasks_user_category')
        batch_op.drop_index(batch_op.f('ix_improvement_tasks_turn_id'))
        batch_op.drop_index(batch_op.f('ix_improvement_tasks_status'))
        batch_op.drop_index('ix_improvement_tasks_session_status')
        batch_op.drop_index(batch_op.f('ix_improvement_tasks_session_id'))
        batch_op.drop_index(batch_op.f('ix_improvement_tasks_id'))
        batch_op.drop_index(batch_op.f('ix_improvement_tasks_created_at'))
        batch_op.drop_index(batch_op.f('ix_improvement_tasks_category'))

    op.drop_table('improvement_tasks')
    with op.batch_alter_table('resume_project_descriptions', schema=None) as batch_op:
        batch_op.drop_index('ix_resume_project_descriptions_user_session')
        batch_op.drop_index(batch_op.f('ix_resume_project_descriptions_user_id'))
        batch_op.drop_index('ix_resume_project_descriptions_user_created')
        batch_op.drop_index(batch_op.f('ix_resume_project_descriptions_target_job_id'))
        batch_op.drop_index(batch_op.f('ix_resume_project_descriptions_session_id'))
        batch_op.drop_index(batch_op.f('ix_resume_project_descriptions_id'))
        batch_op.drop_index(batch_op.f('ix_resume_project_descriptions_created_at'))

    op.drop_table('resume_project_descriptions')
    with op.batch_alter_table('interview_turns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_interview_turns_user_id'))
        batch_op.drop_index('ix_interview_turns_user_created')
        batch_op.drop_index('ix_interview_turns_session_main')
        batch_op.drop_index(batch_op.f('ix_interview_turns_session_id'))
        batch_op.drop_index(batch_op.f('ix_interview_turns_parent_turn_id'))
        batch_op.drop_index(batch_op.f('ix_interview_turns_id'))

    op.drop_table('interview_turns')
    with op.batch_alter_table('agent_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_runs_user_id'))
        batch_op.drop_index('ix_agent_runs_user_created')
        batch_op.drop_index(batch_op.f('ix_agent_runs_status'))
        batch_op.drop_index(batch_op.f('ix_agent_runs_session_id'))
        batch_op.drop_index('ix_agent_runs_session_created')
        batch_op.drop_index('ix_agent_runs_run_id')
        batch_op.drop_index(batch_op.f('ix_agent_runs_request_id'))
        batch_op.drop_index(batch_op.f('ix_agent_runs_id'))
        batch_op.drop_index(batch_op.f('ix_agent_runs_created_at'))
        batch_op.drop_index(batch_op.f('ix_agent_runs_agent_name'))

    op.drop_table('agent_runs')
    with op.batch_alter_table('interview_sessions', schema=None) as batch_op:
        batch_op.drop_index('ix_interview_sessions_user_status')
        batch_op.drop_index('ix_interview_sessions_user_mode')
        batch_op.drop_index(batch_op.f('ix_interview_sessions_user_id'))
        batch_op.drop_index('ix_interview_sessions_user_created')
        batch_op.drop_index(batch_op.f('ix_interview_sessions_target_job_id'))
        batch_op.drop_index(batch_op.f('ix_interview_sessions_status'))
        batch_op.drop_index(batch_op.f('ix_interview_sessions_previous_session_id'))
        batch_op.drop_index(batch_op.f('ix_interview_sessions_mode'))
        batch_op.drop_index(batch_op.f('ix_interview_sessions_improvement_status'))
        batch_op.drop_index(batch_op.f('ix_interview_sessions_id'))
        batch_op.drop_index(batch_op.f('ix_interview_sessions_created_at'))

    op.drop_table('interview_sessions')
    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_profiles_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_profiles_id'))

    op.drop_table('user_profiles')
    with op.batch_alter_table('user_data_deletion_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_data_deletion_logs_user_id'))
        batch_op.drop_index('ix_user_data_deletion_logs_user_created')
        batch_op.drop_index(batch_op.f('ix_user_data_deletion_logs_status'))
        batch_op.drop_index(batch_op.f('ix_user_data_deletion_logs_id'))
        batch_op.drop_index(batch_op.f('ix_user_data_deletion_logs_created_at'))

    op.drop_table('user_data_deletion_logs')
    with op.batch_alter_table('usage_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usage_events_user_id'))
        batch_op.drop_index('ix_usage_events_user_date_type_status')
        batch_op.drop_index(batch_op.f('ix_usage_events_usage_type'))
        batch_op.drop_index(batch_op.f('ix_usage_events_usage_date'))
        batch_op.drop_index(batch_op.f('ix_usage_events_status'))
        batch_op.drop_index(batch_op.f('ix_usage_events_id'))
        batch_op.drop_index('ix_usage_events_date_type')

    op.drop_table('usage_events')
    with op.batch_alter_table('upload_reservations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_upload_reservations_user_id'))
        batch_op.drop_index('ix_upload_reservations_user_expires')
        batch_op.drop_index(batch_op.f('ix_upload_reservations_reservation_id'))
        batch_op.drop_index(batch_op.f('ix_upload_reservations_id'))

    op.drop_table('upload_reservations')
    with op.batch_alter_table('target_jobs', schema=None) as batch_op:
        batch_op.drop_index('ux_target_jobs_active_user', sqlite_where=sa.text('is_active = 1'))
        batch_op.drop_index(batch_op.f('ix_target_jobs_user_id'))
        batch_op.drop_index(batch_op.f('ix_target_jobs_is_active'))
        batch_op.drop_index(batch_op.f('ix_target_jobs_id'))

    op.drop_table('target_jobs')
    op.drop_table('registration_settings')
    with op.batch_alter_table('interview_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_interview_records_user_id'))
        batch_op.drop_index(batch_op.f('ix_interview_records_session_id'))
        batch_op.drop_index(batch_op.f('ix_interview_records_id'))

    op.drop_table('interview_records')
    with op.batch_alter_table('history_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_history_records_user_id'))
        batch_op.drop_index(batch_op.f('ix_history_records_record_id'))
        batch_op.drop_index(batch_op.f('ix_history_records_id'))

    op.drop_table('history_records')
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.drop_index('ux_files_user_upload_idempotency', sqlite_where=sa.text('upload_idempotency_key_hash IS NOT NULL'))
        batch_op.drop_index(batch_op.f('ix_files_user_id'))
        batch_op.drop_index(batch_op.f('ix_files_id'))
        batch_op.drop_index(batch_op.f('ix_files_file_id'))

    op.drop_table('files')
    with op.batch_alter_table('daily_usage_counters', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_daily_usage_counters_user_id'))
        batch_op.drop_index(batch_op.f('ix_daily_usage_counters_usage_type'))
        batch_op.drop_index(batch_op.f('ix_daily_usage_counters_usage_date'))
        batch_op.drop_index(batch_op.f('ix_daily_usage_counters_id'))
        batch_op.drop_index('ix_daily_usage_counters_date_type')

    op.drop_table('daily_usage_counters')
    with op.batch_alter_table('auth_sessions', schema=None) as batch_op:
        batch_op.drop_index('ix_auth_sessions_user_revoked')
        batch_op.drop_index(batch_op.f('ix_auth_sessions_user_id'))
        batch_op.drop_index('ix_auth_sessions_revoked_at')
        batch_op.drop_index('ix_auth_sessions_expires_at')

    op.drop_table('auth_sessions')
    with op.batch_alter_table('auth_security_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_auth_security_events_user_id'))
        batch_op.drop_index('ix_auth_security_events_user_created')
        batch_op.drop_index('ix_auth_security_events_type_created')
        batch_op.drop_index(batch_op.f('ix_auth_security_events_id'))
        batch_op.drop_index(batch_op.f('ix_auth_security_events_event_type'))
        batch_op.drop_index(batch_op.f('ix_auth_security_events_created_at'))

    op.drop_table('auth_security_events')
    with op.batch_alter_table('admin_audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_admin_audit_logs_target_user_id'))
        batch_op.drop_index('ix_admin_audit_logs_target_created')
        batch_op.drop_index('ix_admin_audit_logs_status_created')
        batch_op.drop_index(batch_op.f('ix_admin_audit_logs_status'))
        batch_op.drop_index(batch_op.f('ix_admin_audit_logs_id'))
        batch_op.drop_index(batch_op.f('ix_admin_audit_logs_created_at'))
        batch_op.drop_index(batch_op.f('ix_admin_audit_logs_admin_user_id'))
        batch_op.drop_index('ix_admin_audit_logs_admin_created')
        batch_op.drop_index('ix_admin_audit_logs_action_created')
        batch_op.drop_index(batch_op.f('ix_admin_audit_logs_action'))

    op.drop_table('admin_audit_logs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_id'))

    op.drop_table('users')
    with op.batch_alter_table('rate_limit_buckets', schema=None) as batch_op:
        batch_op.drop_index('ix_rate_limit_buckets_subject')
        batch_op.drop_index(batch_op.f('ix_rate_limit_buckets_id'))
        batch_op.drop_index('ix_rate_limit_buckets_expires_at')

    op.drop_table('rate_limit_buckets')
    # ### end Alembic commands ###
